### ISSUE TITLE
Feature request/PR proposal to expose queue URL & Name

### ISSUE THREAD

**Issue by lilfelix** [aws-samples/amazon-sqs-dlq-replay-backoff#2]
Hi! 
I would like to use this app, but currently only the ARNs of the queues are exposed as Output variables.
In my use case (which I believe is a common one) I need to pass in a queue URL as ENV to a lambda function.
I have two questions:

1. Are there good reasons not to expose the queue URL and Name? That way, a user could use the queue name, ARN, or URL as they see fit.
2.  Is there a simple way to enqueue a record to an SQS queue given only its ARN (I know of [GetQueueUrl](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html) via AWS CLI, but that seems like an unnecessarily complexity solution)

The current Outputs in `template.yml` are: 
```
Outputs:
  ReplayFunction:
    Description: "Lambda Function Name"
    Value: !Ref ReplayFunction
  MainQueueArn:
    Description: "Main SQS queue ARN"
    Value: !GetAtt MainQueue.Arn
  ReplayDeadLetterQueue:
    Description: "Replay SQS dead letter queue ARN, managed by the Lambda Function"
    Value: !GetAtt 'ReplayDeadLetterQueue.Arn'
  DeadLetterQueue:
    Description: "SQS dead letter queue ARN, managed manually"
    Value: !GetAtt 'DeadLetterQueue.Arn'
```

My proposal is:
```
Outputs: 
...
  MainQueueARN:
    Description: "Main SQS queue ARN"
    Value: !GetAtt MainQueue.Arn
  MainQueueURL: 
    Description: "Main SQS queue URL"
    Value: !Ref MainQueue
  MainQueueName: 
    Description: "Main SQS queue name"
    Value: !GetAtt MainQueue.QueueName
        
  ... repeat for ReplayDeadLetterQueue and DeadLetterQueue
```

I also noticed that the three outputs for the `MainQueue` have inconsistent naming.
`MainQueueArn`, `ReplayDeadLetterQueue` and `DeadLetterQueue` are all ARNs, but only one of them has ARN in its name. 

I'd be happy to submit a PR if you think exposing URL and Name is a good idea.

Best,
Felix
